config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
   root "pins#index"


  get "about" => "pages#about"


resources :pins do
  member do
    put "like", to: "pins#upvote"
    put "unlike", to: "pins#downvote"
  end
end
  
  
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>", :large => "1024x768>" }, :default_url => "https://s3.amazonaws.com/rememberch/site_files/image_missing.png"
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	validates :image, presence: true
  validates :description, presence: true

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,

         :omniauthable, :omniauth_providers => [:facebook]


         has_many :pins
         validates :name, presence: true

          def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
       # user.name = auth.info.first_name
        # user.name = oauth_data["info"]["first_name"]
        user.name = auth.info.name
        # user.image = auth.info.image

        # user.image = "http://graph.facebook.com/#{self.uid}/picture?type=normal"

        # user.image = "#{options[:secure_image_url] ? 'https' : 'http'}://graph.facebook.com/#{uid}/picture?type=square",

        user.image = auth["info"]["image"]


      end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!

  protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
 
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

 
  
  def index
   @pins = Pin.all.order(:cached_votes_score => :desc).paginate(:page => params[:page], :per_page => 8)
 end





  def show
  end

  def new
    @pin = current_user.pins.build 
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
   
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

    def upvote 
  @pin = Pin.find(params[:id])
  @pin.upvote_by current_user
  redirect_to :back
end  


def downvote
  @pin = Pin.find(params[:id])
  @pin.downvote_by current_user
  redirect_to :back
end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end



  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">

  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

 


<p>
<%= link_to image_tag("https://s3.amazonaws.com/rememberch/site_files/oldwell.jpg", :class => "navbar-brand", :style => "margin: 0px; float: none; width: 85px; height: 104px;"), root_path %>

  RememberChapelHill.com</p>

<% if false %>
code to comment

    <%= link_to image_tag("https://s3.amazonaws.com/rememberch/site_files/logo1.png", :class => "navbar-brand", :style => "margin: 0px; float: none; width: 468px; height: 144px;"), root_path %>
    <% end %>


  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 
      

      <% if user_signed_in? %>

 <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> Upload New Photo
            <% end %>
          </li>

      
      <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>

           <li><%= link_to "Sign up with Facebook", user_omniauth_authorize_path(:facebook), :class => "popup", :"data-width" => 600, :"data-height" => 400 %></li>




        <% end %>


    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RememberChapelHill.com: Share Your Experience!</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  
</head>
<body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=996576647057893";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>




	<%= render 'layouts/header' %>

	<div class="container">

		<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

		<%= yield %>
	</div>


  <% if user_signed_in? %>

  <div id='bottom-right-corner'> Welcome, <%= current_user.name %> ! <br> 
<%= image_tag(current_user.image) %>
     </div>



  <% else %>

<div id='bottom-right-corner'> 
  <%=link_to( image_tag("https://s3.amazonaws.com/rememberch/site_files/fb_login.png", :style => "width: 250px; height: 50px;"), user_omniauth_authorize_path(:facebook), :class => "popup", :"data-width" => 600, :"data-height" => 400) %>


  <% end %>


</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="clearfix top_buttons">
<p>
	<%= link_to "Create my Account", new_user_registration_path, {:class => "btn btn-primary btn-lg pull-right", :style => "margin-left:10px;"}  %> 
	<%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg pull-right" %>
</p>
</div>

<div class="jumbotron">
	<h2>Share your memories in Chapel Hill!</h2>

	<% if user_signed_in? %>
          # do something
     <% else %>




	 <% end %>
</div>

app/views/pages/about.html.erb
<h1>About Us</h1>

<p>We are working on our one month rails pinteresting app.</p>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <p><%= pin.description %></p>
        <p><strong><%= pin.user.name if pin.user %></strong></p>

        <p><%= image_tag(pin.user.image) %></p>
        
        <% if current_user && pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>

<%= link_to like_pin_path(pin), method: :put do %>

  <span class="glyphicon glyphicon-thumbs-up"></span>
  Like
  <%= pin.get_upvotes.size %>
<% end %>

<%= link_to unlike_pin_path(pin), method: :put do %>
<br>
<span class="glyphicon glyphicon-thumbs-down"></span>
  Dislike
  <%= pin.get_downvotes.size %>
<% end %>


          </div>
        <% end %>
        
      </div>
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>Upload and Share a New Photo:</h1> <span class="glyphicon glyphicon-upload"></span>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="row2 center">
    <div class="panel panel-info">
    <div class="panel-heading center">
      <%= image_tag @pin.image.url(:large), class: "img-responsive" %>
    </div>
    <div class="panel-body center">
    <p><%= @pin.description %></p>
    <p><strong><%= @pin.user.name if @pin.user %></strong></p>


    <p><%= image_tag(@pin.user.image) %></p>


    <% if @pin.user == current_user %>
      <%= link_to edit_pin_path(@pin) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
    <% end %>
    </div>
  </div>


<% $pin = @pin.id %>
<div class="fb-comments" data-href="https://rememberch.herokuapp.com?pin=<%= $pin %>" data-width="500" data-numposts="5"></div>



</div>